site_name: App Model
site_url: https://github.com/pyapp-kit/app-model
site_author: Talley Lambert
site_description: Generic application schema implemented in python.

repo_name: pyapp-kit/app-model
repo_url: https://github.com/pyapp-kit/app-model

copyright: Copyright &copy; 2021 - 2022 Talley Lambert

watch:
  - src

plugins:
  - search
  - autorefs
  - minify:
      minify_html: true
  - macros:
      module_name: docs/_macros
  - mkdocstrings:
      handlers:
        python:
          import:
            - https://docs.python.org/3/objects.inv
          options:
            docstring_style: numpy
            show_bases: false
            merge_init_into_class: yes
            show_source: no
            show_root_full_path: no
            show_root_heading: yes
            docstring_section_style: list


markdown_extensions:
  - tables
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - admonition

theme:
  name: material
  icon:
    repo: material/github
    logo: material/application-cog-outline
  features:
    - navigation.instant
    - search.highlight
    - search.suggest
